name: $(SourceBranchName).$(Rev:r)
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - group: var-static-app
stages:
  - stage:
    displayName: "Integração Continua"
    jobs:
      - job: CI
        displayName: CI
        steps:
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(Build.SourcesDirectory)'
              includeRootFolder: true
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              replaceExistingArchive: true
          - task: PublishBuildArtifacts@1
      - job: validaton
        dependsOn: CI
        displayName: 'Manual Validation'
        pool: server
        steps:
            - task: ManualValidation@1
              timeoutInMinutes: 770
              inputs:
                instructions: "Deseja realizar a publicação agora?"
                notifyUsers: 'pedroasmaia@outlook.com'
                approvers: 'pedroasmaia@outlook.com'
      - job: cd
        displayName: CD
        dependsOn: validaton
        steps:
        - task: AzureStaticWebApp@0
          inputs:
            workingDirectory: '$(Build.SourcesDirectory)'
            app_location: '/'
            skip_app_build: true
            azure_static_web_apps_api_token: '$(TokenDeploy)'