
trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage:
    displayName: "Integração Continua"
    jobs:
      - job: CIvalidation
        displayName: CI
        steps:
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(build.sourcesDirectory)'
              includeRootFolder: false
          - task: PublishBuildArtifacts@1
